export { Diagnostics } from "./Diagnostics/Diagnostics";
export { Head } from "./Head/Head";
export { Link } from "../../../components/Link/Link";
export { Makers } from "./Makers/Makers";
export { OurWork } from "./OurWork/OurWork";
export { Services } from "./Services/Services";
export { WhyUs } from "./WhyUs/WhyUs";
export { FAQ } from "./FAQ/FAQ";
export { Contacts } from "./Contacts/Contacts";